server:
  port: 8080

spring:
  application:
    name: DoAn
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 15082004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: manhquan0415@gmail.com
    password: pgxowyyzzhpvvhew
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:BusTicketSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm2024}
    access-token-expiration: 86400000
    refresh-token-expiration: 604800000
  google:
    client-id: ${GOOGLE_CLIENT_ID:400240580082-v6fd1g4pe1v8nddj068rfse9i66mb6lg.apps.googleusercontent.com}
  cors:
    allowed-origins: http://localhost:5173

vnpay:
  tmn-code: Q81NNNN7 # TMN code sandbox của VNPay
  hash-secret: 5O2I37T6EFDHV6HIOTVXSF7T657RFEA9  # Secret key sandbox
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/vnpay/callback
